---
- hosts: app
  remote_user: root
  tasks:
    - name: "nginx setup"
      apt:
        update_cache: yes
        name: nginx
        state: present
    - name: "nginx start using custom module"
      service_status:
        service: nginx
        state: present
    - name: "custom plugin output method a"
      debug:
        msg: "{{'test'|a_filter}}"
    - name: "custom plugin output method b"
      debug:
        msg: "{{'test'|another_filter('the','filters')}}"
