---
- hosts: app
  remote_user: root
  tasks:
    - name: "nginx setup"
      apt:
        update_cache: yes
        name: nginx
        state: present
    - name: "nginx start"
      service_status:
        service: nginx
        state: present
